config/routes.rb
Rails.application.routes.draw do
	
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new' 
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :to_do_lists,          only: [:create, :destroy, :update]

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/to_do_list.rb
class ToDoList < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
  validates :user_id, presence: true

  # Make a description just like a micropost
  validates :description, presence: true, length: { maximum: 140 }
  default_scope -> { order(created_at: :desc) }

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :to_do_list, dependent: :destroy
	attr_accessor :remember_token

	before_save { self.email = self.email.downcase }
	validates(:name,  presence: true, length: { maximum: 50  })
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates(:email, presence: true, length: { maximum: 255 }, 
				      format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false })
	has_secure_password
	validates(:password, presence: true, length: { minimum: 6 })

	# Returns the hash digest of the given string.
	def User.digest(string)
	  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
	  BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token.
	def User.new_token
	  SecureRandom.urlsafe_base64
	end

	# Remembers a user in the database for use in persistent sessions.
    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
      return false if remember_token.nil?
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # Forget a user 
    def forget 
      update_attribute(:remember_digest, nil)
    end

    def feed(tag_id)
    	if tag_id
    		ToDoList.where("user_id = ? and status = ? and tag_id = ?", id, 1, tag_id)
    	else 
        ToDoList.where("user_id = ? and status = ?", id, 1)
    	end
    	
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create 
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
  	else 
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @tag = params[:tag_id]
  	@newtask = current_user.to_do_list.build if logged_in?
  	@feed_items = current_user.feed(@tag).paginate(page: params[:page]) if logged_in?
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/to_do_lists_controller.rb
class ToDoListsController < ApplicationController
  
  before_action :logged_in_user, only: [:create, :destroy, :update]
  before_action :correct_user,   only: [:destroy, :update]

  def create
  	@newtask = current_user.to_do_list.build(to_do_list_params)
    @newtask.status = 1;
  	if @newtask.save
  	  flash[:success] = "New task added"
  	  redirect_to root_url
  	else 
      @feed_items = current_user.to_do_list.where("status = ?", 1).paginate(page: params[:page])
  	  render 'static_pages/home'
  	end
  end

  def destroy
    @todolist.update_attributes!(:status => 0)
    flash[:success] = "Task completed!"
    redirect_to request.referrer || root_url
  end

  def update
    @todolist.update_attributes!(:status => 1)
    flash[:success] = "Task recovered!"
    redirect_to request.referrer || root_url
  end
	
  private

  	# In this function, data will be got from the form
    def to_do_list_params
      params.require(:to_do_list).permit(:description, :tag_id)
    end

    def correct_user
      @todolist = current_user.to_do_list.find_by(id: params[:id])
      redirect_to root_url if @todolist.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @user
  	else 
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
    if !params[:task_status].nil?
      @to_do_lists = @user.to_do_list.where("status = ?", params[:task_status]).paginate(page: params[:page])
    else 
      @to_do_lists = @user.to_do_list.paginate(page: params[:page])
    end
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "My ToDoList"
		if page_title.empty?
			base_title
		else 
			page_title + " | " + base_title
		end
	end

	def tag_name(task_id)
		Tag.find_by(id: task_id).name
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Logs in the given user.
	def log_in(user)
	  session[:user_id] = user.id
	end

	def log_out
	  forget(current_user)
	  session.delete(:user_id)
	  @current_user = nil
	end

	def current_user
	  if (user_id = session[:user_id]) 
	  	@current_user ||= User.find_by(id: user_id)
	  elsif (user_id = cookies.signed[:user_id])
	  	user = User.find_by(id: user_id)
	  	if user && user.authenticated?(cookies[:remember_token])
	  	  log_in user
	  	  @current_user = user
	  	end
	  end
	end

	def logged_in?
	  !current_user.nil?
	end

	def remember(user)
	  user.remember
	  cookies.permanent.signed[:user_id] = user.id
	  cookies.permanent[:remember_token] = user.remember_token
	end

	def forget(user)
	  user.forget
	  cookies.delete(:user_id)
	  cookies.delete(:remember_token)
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/to_do_lists_helper.rb
module ToDoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user) 
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Powered
    by <a href="https://www.facebook.com/profile.php?id=100005438507300">Yang Zhuohan</a> from National University of Singapore
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "My ToDoList", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="todolists">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% else %>
  <div style="text-align:center; padding-top:120px; color:grey">
  	<sapn>It seems that you have finished all your tasks! d(`･∀･)b</span><br>
  	<span><==&nbsp;&nbsp;Wanna add one there? (灬ºωº灬)&nbsp;&nbsp;==</span><br>
  </div>
<% end %>

app/views/shared/_todolist_form.html.erb
<%= form_for(@newtask) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<h4>Task</h4>
    <%= f.text_area :description, placeholder: "Compose new task...",class: "form-control", rows: 5 %>
    <p style="font-size:10px">Describe your task in no more than 140 words</p>
    <%= f.label :tag_id %>
    <%= f.select :tag_id, [['None', 0], ['Family', 1], ['Work', 2], ['Study', 3], ['Activity', 4], ['Relationship', 5]], class: "form-control" %>
  </div>
  <%= f.submit "Add!", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span>To Be Done <span class="badge"><%= current_user.to_do_list.where("status = ?", 1).count %></span></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<div class="well">
	This is an simple app designed by <a href="https://www.facebook.com/profile.php?id=100005438507300">Yang Zhuohan (Bill)</a>, following the tutorial provided by <i><a href="https://www.railstutorial.org/book/frontmatter">RUBY ON RAILS TUTORIAL (3RD ED.)</a></i>.<br>This app is for users to add their tasks to a to-do-list so that they can remember what to do.
 </div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<div class="well">
  Email address: billstark1996@gmail.com.<br>
  QQ number: 624665752<br>
  FaceBook: <a href="https://www.facebook.com/profile.php?id=100005438507300">Yang Zhuohan</a><br>
  
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<div class="well">
  <h4>About avatar image</h4><br>Because I am still a new developer for Ruby on Rails, I still do not implement the function that allow users to upload imagesa as avatar. If you want to add an image, please go to <a href="https://en.gravatar.com/">gravatar</a> and use your email address to add avatar picture.<br>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="todolist_form">
        <%= render 'shared/todolist_form' %>
      </section>
    </aside>
    <div class="col-md-8">
    	
    	<!-- In this part I will devide the tasks into categories -->
    	<ul class="nav nav-pills">
		  <% if !@tag %><li class="active"><% else %><li><% end %><%= link_to "To Do List", {:controller => 'static_pages', :action => 'home', :tag_id => nil} %></li>
		  <% if @tag == '1' %><li class="active"><% else %><li><% end %><%= link_to "Family", {:controller => 'static_pages', :action => 'home', :tag_id => 1} %></li>
		  <% if @tag == '2' %><li class="active"><% else %><li><% end %><%= link_to "Work", {:controller => 'static_pages', :action => 'home', :tag_id => 2} %></li>
		  <% if @tag == '3' %><li class="active"><% else %><li><% end %><%= link_to "Study", {:controller => 'static_pages', :action => 'home', :tag_id => 3} %></li>
		  <% if @tag == '4' %><li class="active"><% else %><li><% end %><%= link_to "Activity", {:controller => 'static_pages', :action => 'home', :tag_id => 4} %></li>
		  <% if @tag == '5' %><li class="active"><% else %><li><% end %><%= link_to "Relationship", {:controller => 'static_pages', :action => 'home', :tag_id => 5} %></li>
		</ul>
		<div class="tab-content">
		  <%= render 'shared/feed' %>
		</div>
	    <!-- end -->
      
    </div>
  </div>
<% else %>
	<div class="center jumbotron">
	  <h1>Welcome to the My ToDoList</h1>

	  <h2>
	    Begin your efficient life here!
	  </h2>

	  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	</div>
<% end %>

app/views/to_do_lists/_to_do_list.html.erb
<li id="todolist-<%= to_do_list.id %>">

	  	<span class="content"><%= to_do_list.description %></span>
		<span class="timestamp">
		  Added <%= time_ago_in_words(to_do_list.created_at) %> ago.
		</span>
		
		<% if to_do_list.tag_id != 0 %>
		 <span class="label label-info"><%= tag_name(to_do_list.tag_id) %></span>
		<% end %>
  	<% if current_user == (to_do_list.user) && to_do_list.status == 1 %>
		<span class="label label-success"><%= link_to "Complete!", to_do_list, method: :delete, class: "label" %></span>
	<% else %>
		<span class="label label-warning"><%= link_to "Recover", to_do_list, method: :put, class: "label" %></span>
  	<% end %>
</li>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <span style="color:grey; font-size:12px; margin-top:10px"><%= @user.email %></span>
    </section>
    <section class="task_info">
      <div class="col-sm-4">
        <span id="title">All Tasks</span>
        <span id="num"><%= link_to @user.to_do_list.count, {:controller => 'users', :action => 'show', :task_status => nil} %></span>
      </div>
      <div class="col-sm-4">
        <span id="title">Completed</span>
        <span id="num"><%= link_to @user.to_do_list.where("status = ?", 0).count, {:controller => 'users', :action => 'show', :task_status => 0} %></span>
      </div>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.to_do_list.any? %>
      <% if !params[:task_status] %>
        <h3>All Tasks</h3>
      <% else %>
        <h3>Completed</h3>
      <% end %>
      <ol class="todolists">
        <%= render @to_do_lists %>
      </ol>
      <%= will_paginate @to_do_lists %>
    <% end %>
  </div>
</div>